#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=98

USE_PROCD=1
PROG=/usr/sbin/ntpd
INTERVAL=172800

validate_ntp_section() {
	uci_validate_section system timeserver "${1}" \
		'server:list(host)' 'enabled:bool:1' 'enable_server:bool:0'
}

start_service() {
	local server enabled enable_server peer
	#MSTC,Olivia, before running ioilas check,do not execute ntpd.
	[ "$ifce_automode" == "0x01" ] && return

	validate_ntp_section ntp || {
		echo "validation failed"
		return 1
	}

	[ $enabled = 0 ] && return

	[ -z "$server" ] && return

	# MSTC, Terence, 20160525 append simple log
	[ -n "$server" ] && [ -f /sbin/simple_logrec.sh ] && {
		simple_logrec.sh -w "NTP, start NTP Client"
	}

	procd_open_instance
	procd_set_param command "$PROG" -n
	procd_append_param command -i $INTERVAL
	[ "$enable_server" = "1" ] && procd_append_param command -l
	for peer in $server; do
		procd_append_param command -p $peer
	done
	procd_set_param respawn
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "system"
	procd_add_validation validate_ntp_section
}
