#!/bin/sh /etc/rc.common
#___MSTC___YuLun: trigger the signal for DDNS service
. /lib/functions.sh
START=19
USE_PROCD=1

start_service() {
	config_load ddns
	config_get mode "global" "mode"
	if [ "${mode}" != "0" ]; then
		procd_open_instance
		procd_set_param command /usr/sbin/ddns
		procd_set_param respawn
		procd_close_instance
	else
		/usr/sbin/ddns &
	fi
}
