#!/bin/sh /etc/rc.common

START=97

start() {
	updateability=`/sbin/uci get system.firmware.updateability`
	ifce_automode=`/sbin/uci get network.wan.ifce_automode`

	if [ -f "/tmp/ioilas_done" -o "$ifce_automode" != "0x01" ]; then
	if [ "A$updateability" != "A0" ]; then
		# new FW checking on booting stage will run on hotplug.d/iface/60-auto-fwupdate

		# configure cond to run periodic checking
		/usr/sbin/auto_fwupdate_scheduler &
	fi
	fi
}

